### PR TITLE
Feature/php7.0

### PR DESCRIPTION
**Pull request by nickautomatic**
@marcellegane @peterlarkin Hope you're both well! Opening a PR because this branch (PHP7) is working fine for me on VirtualBox 5.1, but I know you both had trouble with it. My best guess is that was a VirtualBox version issue (you were both on 5.0). If you try updating to 5.1 and find this branch works, then I reckon it should be ok to merge into master (might be worth adding a version number to VirtualBox in the requirements section of the README at the same time).

### CODE REVIEW

**Comment by peterlarkin** [comment]
I haven't had a chance to fully try this yet, I'll see if I can spin up a test over the next week. I know @marcellegane did try to set up a new project with this in the last couple of weeks and still ran into some problems though

**Comment by ow** [comment]
Hey @nickautomatic I'd love to help test this if I can with my existing project - is there an upgrade path from existing instances of crafty-vagrant?

**Comment by nickautomatic** [comment]
@ow Thanks for the offer! If you'd like to test this branch and let us know if it works for you that would be great. I'm afraid there's no specific upgrade path though: we really built Crafty as a quick starting point for new projects, so we've rarely needed to port subsequent Crafty updates back into pre-existing projects.

Having said that, it might be possible to upgrade to a new version of Crafty by doing something along the following lines:

- Perform a DB backup in Craft's admin panel
- At the command line run `vagrant destroy` to destroy the VM
- Merge in the latest version of Crafty
- Run `npm install && vagrant up`
- When the new box is created, run Crafty's `gulp db:restore` task to restore Craft's DB

Alternatively, clone Crafty to a new folder, install as usual, and then try a git pull from your existing project followed by a db restore (I haven't tried this approach, but it might conceivably work...)

I don't know whether either approach will work though, so please proceed with caution, keep backups and do this at your own risk!

**Comment by ow** [comment]
@nickautomatic followed your instructions and the upgrade went without a single hitch. Craft performance on PHP7 is clearly better — not perfect, but I blame dev mode — and I'm much happier! I'm running Windows 10 here, but as I said, it was smooth sailing.

**Comment by nickautomatic** [comment]
@ow Great, glad to hear it worked! Out of interest:

- Did you take the first approach I outlined above or the second? (Useful to know, in case anyone else wants to do this in future)
- What version of VirtualBox are you using? This would be useful to know, since if it's 5.1 then that fits with my hunch that the problems @peterlarkin and @marcellegane were having were to do with VirtualBox version. If it's 5.0 then it _could_ conceivably be an OS thing because like you I'm on Windows 10 while they're on OSX (though having said that, I have also tested it with no problems on OSX with VirtualBox 5.1, so I suspect bumping up the version should get it working either way)

**Comment by nickautomatic** [comment]
@ow Glad to hear it worked! Out of interest:

- Did you take the first approach I outlined or the second? (Would be useful to know in case anyone else wants to do this in future)
- What version of VirtualBox are you using? This would be useful to know because if it's 5.1 it would support my theory that the problems @peterlarkin and @marcellegane were having were to do with VirtualBox version. If it's 5.0 then it _could_ conceivably be an OS thing because like you I was running Windows 10 (though having said that, I've tested it with no problems on OSX with VirtualBox 5.1, so I suspect / hope bumping up the version should get it working either way)

**Comment by ow** [comment]
Hey @nickautomatic I'm on VirtualBox 5.1 already, and it works fine there! I used your first set of steps, which worked fine. I had changed my origin so needed to set another remote to pull the changes, but everything merged cleanly — and I didn't even need to restore my database since the latest dump was in my folder and the bootstrap script imported it 👍

**Pull request merged**
